run_metadata:
  description: Register a file in the pipeline
  local_data_registry_url: https://localhost:8000/api/
  remote_data_registry_url: https://data.scrc.uk/api/
  default_input_namespace: SCRC
  default_output_namespace: soniamitchell
  default_data_store: /Users/SoniaM/datastore/
  # Exactly one of `remote_repo:` or `local_repo:` is necessary.
  # Either of these may contain the submission_script
  local_repo: /Users/Soniam/Desktop/git/SCRC/SCRCdata
  # Exactly one of `script_path:` and `script:` is necessary.
  # This is the submission script
  script: |- # Relative to local_repo
    R -f inst/SCRC/scotgov_deaths/submission_script.R {CONFIG_PATH}
register:
- external_object: raw-mortality-data
  # Who owns the data?
  source_name: Scottish Government Open Data Repository
  source_abbreviation: Scottish Government Open Data Repository
  source_website: https://statistics.gov.scot/
  # Where does the data come from?
  root_name: Scottish Government Open Data Repository
  root: https://statistics.gov.scot/sparql.csv?query=
  path: |
    PREFIX qb: <http://purl.org/linked-data/cube#>
    PREFIX data: <http://statistics.gov.scot/data/>
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
    PREFIX dim: <http://purl.org/linked-data/sdmx/2009/dimension#>
    PREFIX sdim: <http://statistics.gov.scot/def/dimension/>
    PREFIX stat: <http://statistics.data.gov.uk/def/statistical-entity#>
    PREFIX mp: <http://statistics.gov.scot/def/measure-properties/>
    SELECT ?featurecode ?featurename ?areatypename ?date ?cause ?location ?gender ?age ?type ?count
    WHERE {
     ?indicator qb:dataSet data:deaths-involving-coronavirus-covid-19;
       mp:count ?count;
       qb:measureType ?measType;
       sdim:age ?value;
       sdim:causeOfDeath ?causeDeath;
       sdim:locationOfDeath ?locDeath;
       sdim:sex ?sex;
       dim:refArea ?featurecode;
       dim:refPeriod ?period.

       ?measType rdfs:label ?type.
       ?value rdfs:label ?age.
       ?causeDeath rdfs:label ?cause.
       ?locDeath rdfs:label ?location.
       ?sex rdfs:label ?gender.
       ?featurecode stat:code ?areatype;
         rdfs:label ?featurename.
       ?areatype rdfs:label ?areatypename.
       ?period rdfs:label ?date.
    }
  # Metadata
  title: Deaths associated with COVID-19
  description: The weekly, and year to date, provisional number of deaths associated with coronavirus (COVID-19) registered in Scotland.
  unique_name: Scottish deaths involving COVID-19  # or doi
  product_name: records/SARS-CoV-2/scotland/human-mortality
  file_type: csv
  release_date: 2021-04-14 11:34:37
  version: 0.20210414.0
  primary: True
  accessibility: open

write:
- data_product: records/SARS-CoV-2/scotland/human-mortality
  description: human mortality data
  components:
    nhs_health_board/week-covid_related_deaths: number of covid-related deaths per week per nhs health board
    council_area/week-covid_related_deaths: number of covid-related deaths per week per council area
    age_group/week/gender-country-covid_related_deaths: number of covid-related deaths per week per age group, by gender
    age_group/week-persons-country-covid_related_deaths: number of covid-related deaths per week per age group
    location_type/week-covid_related_deaths: number of covid-related deaths per week in care homes, at home, at hospital, and other locations
    nhs_health_board-covid_related_deaths: total number of covid-related deaths per health board per year
    council_area-covid_related_deaths: total number of covid-related deaths per council area per year
    nhs_health_board/week-all_deaths: number of deaths (all causes) per week per nhs health board
    council_area/week-all_deaths: number of deaths (all causes) per week per council area
    age_group/week/gender-country-all_deaths: number of deaths (all causes) per week per age group, by gender
    age_group/week-persons-country-all_deaths: number of deaths (all causes) per week per age group
    location_type/week-all_deaths: number of deaths (all causes) per week in care homes, at home, at hospital, and other locations
    nhs_health_board-all_deaths: total number of deaths (all causes) per nhs health board per year
    council_area-all_deaths: total number of deaths (all causes) per council area per year
    week-persons-scotland-all_deaths-averaged_over_5years: number of deaths (all causes) per week, averaged over 5 years
  version: 0.20210414.0
