scotgov_dz_lookup/scotgov_dz_lookup.csv

scotgov_management/coronavirus-covid-19-management-information.csv
scotgov_management/coronavirus-covid-19-management-information.h5

scotgov_simd_income/scottish-index-of-multiple-deprivation-income-decile.csv
scotgov_simd_income/scottish-index-of-multiple-deprivation-income-quintile.csv
scotgov_simd_income/scottish-index-of-multiple-deprivation-income-rank.csv
scotgov_simd_income/scottish-index-of-multiple-deprivation-income-vigintile.csv
scotgov_simd_income/scottish-index-of-multiple-deprivation-income.h5

scotgov_ur_classification/urban-rural-classification.csv
scotgov_ur_classification/urban-rural-classification.h5

ukgov_eng_oa_shapefile/outputarea_shapefile/Output_Areas__December_2011__Boundaries_EW_BFC.dbf
ukgov_eng_oa_shapefile/outputarea_shapefile/Output_Areas__December_2011__Boundaries_EW_BFC.xml
ukgov_eng_oa_shapefile/outputarea_shapefile/Output_Areas__December_2011__Boundaries_EW_BFC.cpg
ukgov_eng_oa_shapefile/outputarea_shapefile/Output_Areas__December_2011__Boundaries_EW_BFC.prj
ukgov_eng_oa_shapefile/outputarea_shapefile/Output_Areas__December_2011__Boundaries_EW_BFC.shp
ukgov_eng_oa_shapefile/outputarea_shapefile/Output_Areas__December_2011__Boundaries_EW_BFC.shx

ukgov_scot_dz_shapefile/datazone_shapefile/SG_DataZone_Bdry_2011.dbf
ukgov_scot_dz_shapefile/datazone_shapefile/SG_DataZone_Bdry_2011.shp.xml
ukgov_scot_dz_shapefile/datazone_shapefile/SG_DataZone_Bdry_2011.cpg
ukgov_scot_dz_shapefile/datazone_shapefile/SG_DataZone_Bdry_2011.prj
ukgov_scot_dz_shapefile/datazone_shapefile/SG_DataZone_Bdry_2011.sbn
ukgov_scot_dz_shapefile/datazone_shapefile/SG_DataZone_Bdry_2011.sbx
ukgov_scot_dz_shapefile/datazone_shapefile/SG_DataZone_Bdry_2011.shp
ukgov_scot_dz_shapefile/datazone_shapefile/SG_DataZone_Bdry_2011.shx