utils::globalVariables(c(".", "AREAcode", "AREAname", "AllAges", "CCG19CD",
                         "CCG19NM", "CTRY", "Council", "DZ", "DZcode",
                         "DZname", "DataZone", "DataZone2011Code", "HB",
                         "InterZone", "LAD19CD", "LAD19NM", "LHB19CD",
                         "LHB19NM", "LSOA11CD", "LSOA11NM", "MMWard",
                         "MSOA11CD", "MSOA11NM", "OA11CD", "OAcode",
                         "OAname", "SPC", "STP19CD", "STP19NM", "TTWA",
                         "UA19CD", "UA19NM", "URclass", "WD19CD", "WD19NM",
                         "X", "age", "areagrid10km", "areagrid1km",
                         "areatypename", "cause", "check_for_hdf5",
                         "cols", "conversionh5filepath", "gender",
                         "conversionh5version_number", "delete_hdf5_link",
                         "featurecode", "featurename", "full_zone_area",
                         "grid10km_area_proportion", "grid10km_id",
                         "grid1km_area_proportion", "grid1km_id",
                         "grid_matrix", "j", "pivot_longer", "prop",
                         "read.csv", "str_split", "type", "variable"))
